#!/usr/bin/env python

import glob
import json
import os

job1_number = "1325866"
job2_number = "1325867"

squeue_filename = os.path.dirname(__file__) + "/squeue.json"

with open(squeue_filename, "rt") as squeue_stream:
    squeue_dict = json.load(squeue_stream)

squeue_dict["jobs"][0]["job_id"] = job1_number
squeue_dict["jobs"][1]["job_id"] = job2_number

# For unit test purposes, sbatch has written this file that we read here in the fake squeue.
# Output directory environment variable is set by the unit test.
output_directory = os.environ["OUTPUT_DIRECTORY"]

filenames = glob.glob(f"{output_directory}/**/.bxflow/exit_code.txt", recursive=True)

# When the exit code file is written by the bx_task machinery, we signal the job is done.
if len(filenames) > 0:
    squeue_dict["jobs"][0]["job_state"] = "COMPLETED"
    squeue_dict["jobs"][1]["job_state"] = "COMPLETED"

# Emit the squeue results with changed values.
print(json.dumps(squeue_dict, indent=4))
